import os
from playwright.sync_api import sync_playwright

def generate_pdf_report(audit_report: dict, ai_analysis_text: str, output_path: str = "audit_report.pdf") -> str:
    """
    Compiles raw metrics and Gemini analysis into an executive PDF report using Playwright.
    """
    # Convert AI Markdown text into basic HTML formatting
    formatted_lines = []
    for line in ai_analysis_text.split("\n"):
        line = line.strip()
        if not line:
            continue
        if line.startswith("# "):
            formatted_lines.append(f"<h1>{line[2:]}</h1>")
        elif line.startswith("## "):
            formatted_lines.append(f"<h2>{line[3:]}</h2>")
        elif line.startswith("### "):
            formatted_lines.append(f"<h3>{line[4:]}</h3>")
        elif line.startswith("* **") or line.startswith("- **"):
            formatted_lines.append(f"<p>• {line[2:]}</p>")
        else:
            formatted_lines.append(f"<p>{line}</p>")

    html_body = "\n".join(formatted_lines)

    html_template = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8">
        <title>Audit Report - {audit_report.get('domain')}</title>
        <style>
            body {{
                font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
                margin: 40px;
                color: #1f2937;
                line-height: 1.6;
            }}
            .header {{
                border-bottom: 3px solid #2563eb;
                padding-bottom: 12px;
                margin-bottom: 25px;
            }}
            h1 {{ color: #1e3a8a; font-size: 22px; margin-bottom: 6px; }}
            h2 {{ color: #2563eb; font-size: 16px; margin-top: 20px; border-bottom: 1px solid #e5e7eb; padding-bottom: 4px; }}
            h3 {{ color: #111827; font-size: 14px; margin-top: 12px; }}
            .metric-box {{
                background-color: #f8fafc;
                border: 1px solid #e2e8f0;
                border-radius: 6px;
                padding: 15px;
                margin-bottom: 20px;
            }}
            .metric-line {{
                font-size: 13px;
                margin-bottom: 4px;
            }}
            .metric-val {{
                font-weight: bold;
                color: #2563eb;
            }}
            p {{ font-size: 13px; margin-bottom: 6px; }}
            .footer {{
                margin-top: 40px;
                text-align: center;
                font-size: 11px;
                color: #9ca3af;
                border-top: 1px solid #e5e7eb;
                padding-top: 10px;
            }}
        </style>
    </head>
    <body>
        <div class="header">
            <h1>B2B Website Performance & Security Audit</h1>
            <p style="font-size: 13px;">Target Domain: <strong>{audit_report.get('domain')}</strong></p>
        </div>

        <div class="metric-box">
            <div class="metric-line">Page Load Time: <span class="metric-val">{audit_report.get('load_time_seconds')} seconds</span></div>
            <div class="metric-line">SSL Encryption: <span class="metric-val">{"Enabled" if audit_report.get('is_ssl') else "Missing"}</span></div>
            <div class="metric-line">Mobile Viewport: <span class="metric-val">{"Configured" if not audit_report.get('missing_viewport') else "Missing"}</span></div>
            <div class="metric-line">HTTP Status: <span class="metric-val">{audit_report.get('status_code')}</span></div>
        </div>

        <div class="content">
            {html_body}
        </div>

        <div class="footer">
            Generated by B2B Automated Audit Engine
        </div>
    </body>
    </html>
    """

    # Generate PDF via Playwright
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        page = browser.new_page()
        page.set_content(html_template)
        page.pdf(path=output_path, format="A4", print_background=True)
        browser.close()

    print(f"✓ PDF report generated successfully: {output_path}")
    return output_path

if __name__ == "__main__":
    from auditor import audit_website
    from analyzer import analyze_audit_data

    test_domain = "example.com"
    print("1. Running audit...")
    raw_data = audit_website(test_domain)

    print("2. Generating AI executive analysis...")
    ai_summary = analyze_audit_data(raw_data)

    print("3. Building PDF with Playwright...")
    generate_pdf_report(raw_data, ai_summary, "test_audit_report.pdf")